import CardImage1 from '../../../public/images/location/card1.png'
import CardImage2 from '../../../public/images/location/card2.png'
import CardImage3 from '../../../public/images/location/card3.png'
import CardImage4 from '../../../public/images/location/card4.png'
import CardImage5 from '../../../public/images/location/card5.png'
import CardImage6 from '../../../public/images/location/card6.png'
import CardImage7 from '../../../public/images/location/card7.png'
import CardImageGirl from '../../../public/images/location/girlcard.png'
import NcrCard1 from '../../../public/images/location/ncr-card-1.png'
import NcrCard2 from '../../../public/images/location/ncr-card-2.png'
import MumbaiBanner from '../../../public/images/location/mumbai-banner.png'
import PuneBanner from '../../../public/images/location/pune-banner.png'
import KolkataBanner from '../../../public/images/location/kolkata-banner.png'
import HyderabadBanner from '../../../public/images/location/hyderabad-banner.png'
import NcrBanner from '../../../public/images/location/ncr-banner.png'
import Access from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN6.svg'
import Conference from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN1.svg'
import GameRoom from '../../../public/images/locationInside/gameroom.svg'
import Lounge from '../../../public/images/locationInside/lounge.svg'
import Gym from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN19.svg'
import Phonebooth from '../../../public/images/locationInside/phonebooth.svg'
import EventSpace from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN14.svg'
import Cafe from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN15.svg'
import MontClaireCard from '../../../public/images/locationInside/montclaire-card.png'
import PcpCard from '../../../public/images/location/pcp-card.png'


export const Jsons = {
  LocationData: [
    {
      id: 1,
      locationName: "Mumbai",
      BannerImage: MumbaiBanner,
      locationDetail:
        "Mumbai, India's financial powerhouse,  is known for its vibrant culture that seamlessly blends tradition with modernity, fostering a unique and inspiring atmosphere. A pivotal hub for global commerce, the city's extensive infrastructure ensures a balance of connectivity and convenience, offering a dynamic and thriving environment perfect for entrepreneurs. Whether you're starting your venture or expanding your business, Mumbai provides the ideal landscape for innovation and growth.",
      locationInfo: [
        {
          id: 1,
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/pcp-video.mp4",
          posterImage: "/images/locationInside/pcp-poster.png",
          posterMobileImage: "/images/locationInside/pcp-mobile-poster.png",
          locationName: "PCP",
          locationCity: "Lower Parel",
          locationImg: PcpCard,
          locationMobileImg: "/images/location/pcp-mobile.png",
          location1: "Parel Station - 5 min walk",
          location2: "Best for restaurants, commute-friendly",
          location3: "A thriving corporate park in the heart of Mumbai.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Access, title: "24x7 Access" },
            { source: EventSpace, title: "Event spacess" }
          ],
          url: "/mumbai/pcp",
          amentiesBanner: "/images/locationInside/pcp-amenities-banner.png",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ]
        }
      ],
    },
    {
      id: 2,
      locationName: "Pune",
      BannerImage: PuneBanner,
      locationDetail:
        "Celebrated for its blend of education and innovation, Pune is a magnet for corporates and professionals alike. This city merges world-class business facilities with a vibrant cultural scene where you enjoy state-of-the-art office amenities, lush parks, and bustling cafes, all under the backdrop of its inviting climate—making it perfect for those who thrive in a dynamic and supportive work environment.",
      locationInfo: [
        {
          id: 1,
          bannerImage: "/images/locationInside/westport-banner.png",
          mobileBanner: "/images/locationInside/westport-mobile-banner.png",
          locationName: "Westport",
          videourl: "",
          video: false,
          posterImage: "",
          posterMobileImage: "",
          locationCity: "Baner",
          locationImg: CardImage3,
          locationMobileImg: "/images/location/westport-mobile.png",
          location1: "Metro Station - 650 m",
          location2: "Airport - 19 km",
          location3: "The commercial and residential hub of Pune.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: GameRoom, title: "Game room" },
            { source: Access, title: "24x7 Access" }
          ],
          url: "/pune/westport",
          amentiesBanner: "/images/locationInside/westport-amenities-banner.png",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
            { img: Cafe, title: "Cafetaria area" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        },
        {
          id: 2,
          locationName: "Sai radhe",
          bannerImage: "/images/location/sai-radhe-banner.png",
          mobileBanner: "/images/locationInside/sairadhe-mobile-banner.png",
          videourl: "",
          video: false,
          posterImage: "",
          posterMobileImage: "",
          locationCity: "Bund Garden",
          locationImg: CardImage6,
          locationMobileImg: "/images/location/sairadhe-mobile.png",
          location1: "Metro Station - 100 m",
          location2: "Airport - 6km",
          location3: "A thriving corporate park in the heart of Pune.",
          amentiesBanner: "/images/locationInside/sairadhe-amenities-banner.png",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Gym, title: "Gym" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/pune/sai-radhe",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: Gym, title: "Gym" },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        },
        {
          id: 3,
          locationName: "Koncord",
          locationCity: "Bund Garden",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/koncard-video.mp4",
          posterImage: "/images/locationInside/koncard-poster.png",
          posterMobileImage: "/images/locationInside/koncard-mobile-poster.png",
          locationImg: CardImage4,
          locationMobileImg: "/images/location/koncard-mobile.png",
          location1: "Metro Station - 10 m",
          location2: "Airport - 5.7 km",
          location3: "A thriving corporate park in the heart of Pune.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Gym, title: "Gym" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/pune/koncard",
          amentiesBanner: "/images/locationInside/koncard-amenities-banner.png",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: Gym, title: "Gym" },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        },
        {
          id: 4,
          locationName: "AeroMall",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/areomall-video.mp4",
          posterImage: "/images/locationInside/aeromall-poster.png",
          posterMobileImage: "/images/locationInside/areomall-mobile-poster.png",
          locationCity: "Viman Nagar",
          locationImg: CardImage5,
          locationMobileImg: "/images/location/aeromall-mobile.png",
          location1: "Metro Station - 1 km",
          location2: "Airport - 10 m",
          location3: "A thriving corporate park in the heart of Pune.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Gym, title: "Gym" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/pune/aeromall",
          amentiesBanner: "/images/locationInside/aeromall-amenities-banner.png",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: Gym, title: "Gym" },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        },
        {
          id: 5,
          locationName: "Nandan probiz",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/nandan-video.mp4",
          posterImage: "/images/locationInside/nandan-poster.png",
          posterMobileImage: "/images/locationInside/nandan-mobile-poster.png",
          locationCity: "Balewadi",
          locationImg: CardImageGirl,
          locationMobileImg: "/images/location/nandan-mobile.png",
          location1: "Metro Station - 200 m",
          location2: "Airport - 19 km",
          location3: "A thriving corporate park in the heart of Pune.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Gym, title: "Gym" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/pune/nandan-probiz",
          amentiesBanner: "/images/locationInside/nandanprobiz-amenities-banner.png",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        },
        {
          id: 6,
          bannerImage: "/images/locationInside/montclaire-banner.png",
          mobileBanner: "/images/locationInside/montclaire-mobile-banner.png",
          locationName: "Montclaire",
          videourl: "",
          video: false,
          posterImage: "",
          posterMobileImage: "",
          locationCity: "Baner",
          locationImg: MontClaireCard,
          locationMobileImg: "/images/location/montclaire-mobile.png",
          location1: "Metro Station - 850 m",
          location2: "Airport - 16.5 km",
          location3: "A thriving corporate park in the heart of Pune.",
          amentiesBanner: "/images/locationInside/westport-amenities-banner.png",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Phonebooth, title: "Phonebooth" },
            { source: GameRoom, title: "Game room" }
          ],
          url: "/pune/montclaire",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
            { img: Cafe, title: "Cafetaria area" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        },
        {
          id: 7,
          bannerImage: "/images/location/pentagon-banner.png",
          mobileBanner: "/images/locationInside/pentagon-mobile-banner.png",
          locationName: "Pentagon 5",
          videourl: "",
          video: false,
          posterImage: "",
          posterMobileImage: "",
          locationCity: "Magarpatta",
          locationImg: CardImage7,
          locationMobileImg: "/images/location/pentagon-mobile.png",
          location1: "Metro Station - 5.4 km",
          location2: "Airport - 9 km",
          location3: "A thriving corporate park in the heart of Pune.",
          amentiesBanner: "/images/locationInside/pentagon-amenities-banner.png",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Gym, title: "Gym" },
            { source: GameRoom, title: "Game room" }
          ],
          url: "/pune/pentagon",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: Gym, title: "Gym" },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        },
      ],
    },
    {
      id: 3,
      locationName: "Kolkata",
      BannerImage: KolkataBanner,
      locationDetail:
        "As a major economic and commercial hub in Eastern India, Kolkata offers a dynamic blend of old-world charm and modern business opportunities. Kolkata's strong literary and artistic traditions continue to thrive alongside its burgeoning sectors in technology and finance. With its sprawling gardens, historic colleges, and iconic Howrah Bridge, Kolkata remains a city that beautifully marries its past with a progressive present.",
      locationInfo: [
        {
          id: 1,
          bannerImage: "/images/locationInside/technopolis-banner.png",
          mobileBanner: "/images/locationInside/baani-mobile-poster.png",
          locationName: "Technopolis",
          videourl: "",
          video: false,
          posterImage: "",
          posterMobileImage: "",
          locationCity: "Salt Lake",
          locationImg: CardImage1,
          locationMobileImg: "/images/location/kolkata-mobile.png",
          location1: "Metro Station - 1.8 km",
          location2: "Airport - 9.7 km",
          location3: "India’s first LEED certified Green IT Park.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Cafe, title: "Live kitchen" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/kolkata/technopolis",
          amentiesBanner: "/images/locationInside/technopolis-amenities-banner.png",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Cafe, title: "Live kitchen" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "Live kitchen" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        }
      ],
    },
    {
      id: 4,
      locationName: "Hyderabad",
      BannerImage: HyderabadBanner,
      locationDetail:
        "Hyderabad blends its rich heritage with a strong technological footprint. Renowned for its historic sites, the city is equally celebrated for its thriving IT industry and biotechnology research. Hyderabad's vibrant culture is mirrored in its diverse cuisine, bustling markets, and the warmth of its people. With extensive development in modern business parks and residential areas, it offers a unique mix of tradition and modernity, making it a compelling city for professionals and tourists alike.",
      locationInfo: [
        {
          id: 1,
          locationName: "Raheja Mindspace",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/hyderabad-video.mp4",
          posterImage: "/images/locationInside/raheja-poster.png",
          posterMobileImage: "/images/locationInside/maxhouse-mobile-poster.png",
          locationCity: "Htec city",
          locationImg: CardImage2,
          locationMobileImg: "/images/location/hyderabad-mobile.png",
          location1: "Metro Station - 500 m",
          location2: "Airport - 33 km",
          location3: "One of India’s leading tech industry hub.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: GameRoom, title: "Game room" },
            { source: Access, title: "24x7 Access" },
          ],
          url: "/hyderabad/raheja-mindspace",
          amentiesBanner: "/images/locationInside/rahejamindspace-amenities-banner.png",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
            { img: Cafe, title: "Live kitchen" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Cafe, title: "Live kitchen" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        }
      ],
    },
    {
      id: 4,
      locationName: "NCR",
      BannerImage: NcrBanner,
      locationDetail:
        "The National Capital Region (NCR) of India, encompassing Delhi, Gurgaon and surrounding districts, is a thriving economic hub with immense opportunities for enterprises and startups. This region, known for its excellent connectivity, hosts a range of industries such as Information Technology, telecommunications, manufacturing, and real estate, making it an attractive destination for businesses to flourish. With its dynamic economy, robust infrastructure and a culture of new-age innovation, NCR is an ideal destination for enterprises seeking growth and success in a competitive market.",
      locationInfo: [
        {
          id: 1,
          locationName: "Baani, The Statement",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/baani-video.mp4",
          posterImage: "/images/locationInside/baani-poster.png",
          posterMobileImage: "/images/locationInside/technopolis-mobile-banner.png",
          locationCity: "Gurgaon",
          locationImg: NcrCard1,
          locationMobileImg: "/images/location/baani-mobile.png",
          location1: "Metro Station - 500 m",
          location2: "Airport - 13.6 km",
          location3: "One of India’s leading tech industry hub.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Gym, title: "Gym" },
            { source: Conference, title: "Outdoor space" },
          ],
          url: "/ncr/baani",
          amentiesBanner: "/images/locationInside/baani-amenities-banner.png",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Conference, title: "Outdoor space" },
            { img: Cafe, title: "Live kitchen" },
            { img: Phonebooth, title: "Phonebooth" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Cafe, title: "Live kitchen" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: Phonebooth, title: "Phonebooth" },
            { img: Gym, title: "Gym" },
            { img: GameRoom, title: "Game room" },
            { img: Conference, title: "Outdoor space" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
          ],
        },
        {
          id: 2,
          locationName: "Max House",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/maxhouse-video.mp4",
          posterImage: "/images/locationInside/maxhouse-poster.png",
          posterMobileImage: "/images/locationInside/raheja-mobile-poster.png",
          locationCity: "Okhla",
          locationImg: NcrCard2,
          locationMobileImg: "/images/location/maxhouse-mobile.png",
          location1: "Metro Station - 1 km",
          location2: "Airport - 16.6 km",
          location3: "One of India’s leading tech industry hub.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Phonebooth, title: "Phonebooth" },
            { source: Access, title: "24x7 Access" },
          ],
          url: "/ncr/max-house",
          amentiesBanner: "/images/locationInside/maxhouse-amenities-banner.png",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Conference, title: "Outdoor space" },
            { img: Cafe, title: "Cafetaria" },
            { img: Lounge, title: "Event spaces" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Cafe, title: "Cafetaria area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 security" },
          ],
        }
      ],
    },
  ],
};
