import CardImage1 from '../../../public/images/location/card1.png'
import CardImage2 from '../../../public/images/location/card2.png'
import CardImage3 from '../../../public/images/location/card3.png'
import CardImage4 from '../../../public/images/location/card4.png'
import CardImage5 from '../../../public/images/location/card5.png'
import CardImage6 from '../../../public/images/location/card6.png'
import CardImage7 from '../../../public/images/location/card7.png'
import CardImageGirl from '../../../public/images/location/girlcard.png'
import NcrCard1 from '../../../public/images/location/ncr-card-1.png'
import NcrCard2 from '../../../public/images/location/ncr-card-2.png'
import MumbaiBanner from '../../../public/images/location/mumbai-banner.png'
import PuneBanner from '../../../public/images/location/pune-banner.png'
import KolkataBanner from '../../../public/images/location/kolkata-banner.png'
import HyderabadBanner from '../../../public/images/location/hyderabad-banner.png'
import NcrBanner from '../../../public/images/location/ncr-banner.png'
import GurgaonBanner from '../../../public/images/location/gurgaonBanner.jpg'
import Access from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN6.svg'
import Conference from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN1.svg'
import GameRoom from '../../../public/images/locationInside/gameroom.svg'
import Lounge from '../../../public/images/locationInside/lounge.svg'
import Gym from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN19.svg'
import Phonebooth from '../../../public/images/locationInside/phonebooth.svg'
import EventSpace from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN14.svg'
import Cafe from '../../../public/images/solutionsLanding/logoAmenities/amenitiesN15.svg'
import MontClaireCard from '../../../public/images/locationInside/montclaire-card.png'
import PcpCard from '../../../public/images/location/pcp-card.png'


export const Jsons = {
  LocationData: [
    {
      id: 1,
      bannerAlt: "commercial property in Mumbai",
      locationName: "Mumbai",
      BannerImage: MumbaiBanner,
      metaTitle: " Ready-To-Work-In Office Space in Mumbai | UrbanWrk",
      metaDescription: "Get your ideal workspace at UrbanWrk, ready-to-work-in/ready to move office spaces in Mumbai with fully equipped meeting rooms for streamlined business operations.",
      locationDetail:
        "Mumbai, with its blend of culture, commerce, and connectivity, offers an unparalleled work environment that's as dynamic as the city itself. Find diverse workspaces from vibrant suburbs to business hubs, all equipped with world-class amenities supported by a dedicated team to make your workday perfect in every way.",
      locationInfo: [
        {
          id: 1,
          cardAlt: "office space in PCP Lower Parel",
          metaTitle: "Custom Workspaces at Peninsula Corporate Park, Mumbai  | UrbanWrk",
          metaDescription: "Explore UrbanWrk's modern workspaces at Peninsula Corporate Park, Mumbai, with meeting rooms, event spaces, and top amenities. Tailor your ideal office with expert design solutions.",
          breadcrumbsTitle: "Peninsula Corporate Park",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/pcp-video.mp4",
          posterImage: "/images/locationInside/pcp-poster.png",
          posterMobileImage: "/images/locationInside/pcp-mobile-poster.png",
          locationName: "Peninsula Corporate Park",
          locationCity: "Lower Parel",
          locationImg: PcpCard,
          locationMobileImg: "/images/location/pcp-mobile.png",
          location1: "Parel Station - 5 min walk",
          location2: "Best for restaurants, commute-friendly",
          location3: "A thriving corporate park in the heart of Mumbai.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Access, title: "24x7 Access" },
            { source: EventSpace, title: "Event spaces" }
          ],
          url: "/mumbai/peninsula-corporate-park",
          amentiesBanner: "/images/locationInside/pcp-amenities-banner.png",
          amentiesBannerAlt: "tailor-made office in Lower Parel",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ]
        }
      ],
    },
    {
      id: 2,
      bannerAlt: "UrbanWrk Pune",
      locationName: "Pune",
      BannerImage: PuneBanner,
      metaTitle: "Premium Managed Office Space in Pune | UrbanWrk",
      metaDescription: "UrbanWrk offers premium managed office spaces in Pune. Explore our flexible workspaces designed for sustainability and innovation, perfect for modern entrepreneurs.",
      locationDetail:
        "Celebrated for its blend of education and innovation, Pune is a magnet for corporates and professionals alike. This city merges world-class business facilities with a vibrant cultural scene where you enjoy state-of-the-art office amenities, lush parks, and bustling cafes, all under the backdrop of its inviting climate—making it perfect for those who thrive in a dynamic and supportive work environment.",
      locationInfo: [
        {
          id: 1,
          cardAlt: "UrbanWrk - Westport Baner",
          locationCardAlt: "UrbanWrk - Westport Baner",
          metaTitle: "State-of-the-Art Workspaces in Pune, Westport | UrbanWrk",
          metaDescription: "Transform your work experience at Westport Pune with UrbanWrk. Discover personalized office spaces, premium amenities, & a dynamic community for growth & collaboration.",
          breadcrumbsTitle: "Westport",
          bannerImage: "/images/locationInside/westport-banner.png",
          mobileBanner: "/images/locationInside/westport-mobile-banner.png",
          bannerAlt: "UrbanWrk - Westport Pune",
          locationName: "Westport",
          videourl: "",
          video: false,
          posterImage: "",
          posterMobileImage: "",
          locationCity: "Baner",
          locationImg: CardImage3,
          locationMobileImg: "/images/location/westport-mobile.png",
          location1: "Metro Station - 650 m",
          location2: "Airport - 19 km",
          location3: "The commercial and residential hub of Pune.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: GameRoom, title: "Game room" },
            { source: Access, title: "24x7 Access" }
          ],
          url: "/pune/westport",
          amentiesBanner: "/images/locationInside/westport-amenities-banner.png",
          amentiesBannerAlt: "modern office space amenities",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
            { img: Cafe, title: "Cafetaria area" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        },
        {
          id: 2,
          cardAlt: "UrbanWrk - Sai Radhe Bund Garden",
          locationCardAlt: "office space in Sai Radhe Bund Garden Pune",
          metaTitle: "Premium Commercial Office Space in Pune, Sai Radhe | UrbanWrk",
          metaDescription: "Experience Sai Radhe's contemporary office spaces in Pune with UrbanWrk . Find flexible work solutions with stunning design and biophilic features for your business.",
          breadcrumbsTitle: "Sai Radhe",
          locationName: "Sai radhe",
          bannerImage: "",
          mobileBanner: "",
          bannerAlt: "Sai Radhe office space in Pune",
          videourl: "/images/locationInside/sai-radhe.mp4",
          video: true,
          posterImage: "/images/location/sai-radhe-banner.png",
          posterMobileImage: "/images/locationInside/sairadhe-mobile-banner.png",
          locationCity: "Bund Garden",
          locationImg: CardImage6,
          locationMobileImg: "/images/location/sairadhe-mobile.png",
          location1: "Metro Station - 100 m",
          location2: "Airport - 6 km",
          location3: "A thriving corporate park in the heart of Pune.",
          amentiesBanner: "/images/locationInside/sairadhe-amenities-banner.png",
          amentiesBannerAlt: "Sai Radhe office amenities",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Gym, title: "Gym" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/pune/sai-radhe",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: Gym, title: "Gym" },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        },
        {
          id: 3,
          cardAlt: "UrbanWrk - Koncord Bund Garden",
          locationCardAlt: "commercial office space in Koncord Pune",
          metaTitle: "Managed Offices with Biophilic Design at Koncord | UrbanWrk",
          metaDescription: "Experience the future of work at Koncord in Pune with UrbanWrk, offering managed offices that prioritize biophilic design and sustainable solutions.",
          breadcrumbsTitle: "Koncord",
          locationName: "Koncord",
          locationCity: "Bund Garden",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/koncard-video.mp4",
          posterImage: "/images/locationInside/koncard-poster.png",
          posterMobileImage: "/images/locationInside/koncard-mobile-poster.png",
          locationImg: CardImage4,
          locationMobileImg: "/images/location/koncard-mobile.png",
          location1: "Metro Station - Right next door",
          location2: "Airport - 5.7 km",
          location3: "A thriving corporate park in the heart of Pune.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Gym, title: "Gym" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/pune/koncord",
          amentiesBanner: "/images/locationInside/koncard-amenities-banner.png",
          amentiesBannerAlt: "modern office amenities at koncord Pune",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: Gym, title: "Gym" },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        },
        {
          id: 4,
          cardAlt: "UrbanWrk - AeroMall Viman Nagar",
          locationCardAlt: "office space in aero mall Pune",
          metaTitle: "Sustainable Commercial Spaces at Aeromall Pune | UrbanWrk",
          metaDescription: "Explore Aeromall in Pune with UrbanWrk, offering flexible commercial spaces that blend  sustainability with exceptional design, for both entrepreneurs and businesses.",
          breadcrumbsTitle: "Aeromall",
          locationName: "Aeromall",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/areomall-video.mp4",
          posterImage: "/images/locationInside/aeromall-poster.png",
          posterMobileImage: "/images/locationInside/areomall-mobile-poster.png",
          locationCity: "Viman Nagar",
          locationImg: CardImage5,
          locationMobileImg: "/images/location/aeromall-mobile.png",
          location1: "Metro Station - 1 km",
          location2: "Airport - 10 m",
          location3: "A thriving corporate park in the heart of Pune.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Gym, title: "Gym" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/pune/aeromall",
          amentiesBanner: "/images/locationInside/aeromall-amenities-banner.png",
          amentiesBannerAlt: "modern amenities at a workplace",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: Gym, title: "Gym" },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        },
        {
          id: 5,
          cardAlt: "UrbanWrk - Nandan Probiz Balewadi",
          locationCardAlt: "managed office space in Nandan Probiz Pune",
          metaTitle: "Best Managed Office Space in Pune, Nandan Probiz | UrbanWrk",
          metaDescription: "Explore Nandan Probiz in Pune with UrbanWrk, offering flexible commercial spaces that blend sustainability with exceptional design for both entrepreneurs and businesses.",
          breadcrumbsTitle: "Nandan Probiz",
          locationName: "Nandan probiz",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/nandan-video.mp4",
          posterImage: "/images/locationInside/nandan-poster.png",
          posterMobileImage: "/images/locationInside/nandan-mobile-poster.png",
          locationCity: "Balewadi",
          locationImg: CardImageGirl,
          locationMobileImg: "/images/location/nandan-mobile.png",
          location1: "Metro Station - 200 m",
          location2: "Airport - 19 km",
          location3: "A thriving corporate park in the heart of Pune.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Gym, title: "Gym" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/pune/nandan-probiz",
          amentiesBanner: "/images/locationInside/nandanprobiz-amenities-banner.png",
          amentiesBannerAlt: "Amenities at Nandan Probiz Pune UrbanWrk office",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        },
        {
          id: 6,
          cardAlt: "UrbanWrk - Montclaire Baner",
          locationCardAlt: "commercial workplace Montclaire Baner",
          metaTitle: "Ready-to-Work-In Office Spaces in MontClaire Pune | UrbanWrk",
          metaDescription: "Discover MontClaire in Pune—your perfect ready-to-work-in office spaces with UrbanWrk. We offer fully furnished, ready to use workspaces.",
          breadcrumbsTitle: "MontClaire",
          bannerImage: "/images/locationInside/montclaire-banner.png",
          mobileBanner: "/images/locationInside/montclaire-mobile-banner.png",
          bannerAlt: "Montclaire office Pune",
          locationName: "MontClaire",
          videourl: "",
          video: false,
          posterImage: "",
          posterMobileImage: "",
          locationCity: "Baner",
          locationImg: MontClaireCard,
          locationMobileImg: "/images/location/montclaire-mobile.png",
          location1: "Metro Station - 850 m",
          location2: "Airport - 16.5 km",
          location3: "A thriving corporate park in the heart of Pune.",
          amentiesBanner: "/images/locationInside/westport-amenities-banner.png",
          amentiesBannerAlt: "modern office space amenities",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms" },
            { source: Phonebooth, title: "Phonebooth" },
            { source: GameRoom, title: "Game room" }
          ],
          url: "/pune/montclaire",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
            { img: Cafe, title: "Cafetaria area" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: Cafe, title: "Cafetaria area" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        },
        // {
        //   id: 7,
        //   cardAlt: "UrbanWrk - Pentagon Magarpatta",
        //   locationCardAlt: "office space in Pentagon Magarpatta Pune",
        //   metaTitle: "Modern Office Solutions with Biophilic Design in Pune, Pentagon | UrbanWrk",
        //   metaDescription: "Experience the future of work at Pentagon in Pune with UrbanWrk, offering managed offices that prioritize biophilic design and sustainable solutions.",
        //   breadcrumbsTitle: "Pentagon",
        //   bannerImage: "/images/location/pentagon-banner.png",
        //   mobileBanner: "/images/locationInside/pentagon-mobile-banner.png",
        //   bannerAlt: "UrbanWrk pentagon office cafeteria",
        //   locationName: "Pentagon",
        //   videourl: "",
        //   video: false,
        //   posterImage: "",
        //   posterMobileImage: "",
        //   locationCity: "Magarpatta",
        //   locationImg: CardImage7,
        //   locationMobileImg: "/images/location/pentagon-mobile.png",
        //   location1: "Metro Station - 5.4 km",
        //   location2: "Airport - 9 km",
        //   location3: "A thriving corporate park in the heart of Pune.",
        //   amentiesBanner: "/images/locationInside/pentagon-amenities-banner.png",
        //   amentiesBannerAlt: "luxury office and its amenities",
        //   AmentiesData: [
        //     { source: Lounge, title: "Lounge area" },
        //     { source: Conference, title: "Conference rooms" },
        //     { source: Gym, title: "Gym" },
        //     { source: GameRoom, title: "Game room" }
        //   ],
        //   url: "/pune/pentagon",
        //   connectivityAmenities: [
        //     { img: Lounge, title: "Lounge area" },
        //     { img: Conference, title: "Conference rooms" },
        //     { img: Gym, title: "Gym" },
        //     { img: Phonebooth, title: "Phonebooth" },
        //     { img: GameRoom, title: "Game room" },
        //     { img: Access, title: "24x7 Access" },
        //   ],
        //   locationInsideAmenities: [
        //     { img: Lounge, title: "Lounge area" },
        //     { img: GameRoom, title: "Game room" },
        //     { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
        //     { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
        //     { img: Gym, title: "Gym" },
        //     { img: Cafe, title: "Cafetaria area" },
        //     { img: Phonebooth, title: "Phonebooth" },
        //     { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
        //     { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
        //     { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
        //     { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
        //     { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
        //   ],
        // },
      ],
    },
    {
      id: 3,
      bannerAlt: "commercial office space in Kolkata",
      locationName: "Kolkata",
      metaTitle: "Customised & Ready-To-Move-In Offices in Kolkata | UrbanWrk",
      metaDescription: "UrbanWrk offers flexible office spaces in Kolkata for diverse business needs & enhanced convenience. Explore our tailor-made solutions for all your needs.",
      BannerImage: KolkataBanner,
      locationDetail:
        "As a major economic and commercial hub in Eastern India, Kolkata offers a dynamic blend of old-world charm and modern business opportunities. Kolkata's strong literary and artistic traditions continue to thrive alongside its burgeoning sectors in technology and finance. With its sprawling gardens, historic colleges, and iconic Howrah Bridge, Kolkata remains a city that beautifully marries its past with a progressive present.",
      locationInfo: [
        {
          id: 1,
          metaTitle: " Customised Corporate Office Space at Technopolis, Kolkata | UrbanWrk",
          metaDescription: "Find your ideal customised office at Technopolis, Kolkata. UrbanWrk offers bespoke private offices with tailored designs, furnishings, and dedicated meeting rooms.",
          breadcrumbsTitle: "Technopolis",
          bannerImage: "",
          mobileBanner: "",
          bannerAlt: "workplace in Kolkata",
          cardAlt: "UrbanWrk Technopolis Kolkata",
          locationName: "Technopolis",
          videourl: "/images/locationInside/technopolis.mp4",
          video: true,
          posterImage: "/images/locationInside/technopolis-banner.png",
          posterMobileImage: "/images/locationInside/baani-mobile-poster.png",
          locationCity: "Salt Lake",
          locationImg: CardImage1,
          locationMobileImg: "/images/location/kolkata-mobile.png",
          location1: "Metro Station - 1.8 km",
          location2: "Airport - 9.7 km",
          location3: "India’s first LEED certified Green IT Park.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Cafe, title: "Live kitchen" },
            { source: Phonebooth, title: "Phonebooth" }
          ],
          url: "/kolkata/technopolis",
          amentiesBanner: "/images/locationInside/technopolis-amenities-banner.png",
          amentiesBannerAlt: "managed office space in Kolkata",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Cafe, title: "Live kitchen" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "Live kitchen" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        }
      ],
    },
    {
      id: 4,
      bannerAlt: "UrbanWrk Hyderabad",
      locationName: "Hyderabad",
      metaTitle: "Premium & Commercial Office Space in Hyderabad | UrbanWrk",
      metaDescription: "Discover premium office spaces in Hyderabad with UrbanWrk. Explore our commercial spaces designed for productivity and innovation. Visit us for more information! Turn on screen reader support",
      BannerImage: HyderabadBanner,
      locationDetail:
        "Hyderabad blends its rich heritage with a strong technological footprint. Renowned for its historic sites, the city is equally celebrated for its thriving IT industry and biotechnology research. Hyderabad's vibrant culture is mirrored in its diverse cuisine, bustling markets, and the warmth of its people. With extensive development in modern business parks and residential areas, it offers a unique mix of tradition and modernity, making it a compelling city for professionals and tourists alike.",
      locationInfo: [
        {
          id: 1,
          cardAlt: "UrbanWrk Raheja Mindspace",
          metaTitle: "Customised Office at Raheja Mindspace Hyderabad | UrbanWrk",
          metaDescription: "Find your ideal customised office at Raheja Mindspace, Hyderabad. UrbanWrk offers exclusive amenities such as breakaway spaces and conference rooms to boost productivity.",
          breadcrumbsTitle: "Raheja Mindspace",
          locationName: "Raheja Mindspace",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/hyderabad-video.mp4",
          posterImage: "/images/locationInside/raheja-poster.png",
          posterMobileImage: "/images/locationInside/maxhouse-mobile-poster.png",
          locationCity: "Hitec city",
          locationImg: CardImage2,
          locationMobileImg: "/images/location/hyderabad-mobile.png",
          location1: "Metro Station - 500 m",
          location2: "Airport - 33 km",
          location3: "One of India’s leading tech industry hub.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: GameRoom, title: "Game room" },
            { source: Access, title: "24x7 Access" },
          ],
          url: "/hyderabad/raheja-mindspace",
          amentiesBanner: "/images/locationInside/rahejamindspace-amenities-banner.png",
          amentiesBannerAlt: "commercial space in Hyderabad",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: GameRoom, title: "Game room" },
            { img: Access, title: "24x7 Access" },
            { img: Cafe, title: "Live kitchen" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Cafe, title: "Live kitchen" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: GameRoom, title: "Game room" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        }
      ],
    },
    {
      id: 4,
      bannerAlt: "workspace in Delhi",
      locationName: "Delhi",
      metaTitle: "Premium Ready-To-Work-In Office Spaces in Delhi | UrbanWrk",
      metaDescription: "UrbanWrk offers fully furnished, ready-to-work-in office spaces in the Delhi. Find your ideal workspace and transform your work environment with our premium offerings.",
      BannerImage: NcrBanner,
      locationDetail:
        "Delhi, the national capital of India, stands as a testament to both historical legacy and modern progress. As the political nerve center of the country, it offers unparalleled advantages for businesses through its world-class infrastructure, including an extensive metro network and international airport connectivity. The city hosts diverse sectors ranging from retail and media to professional services and public sector enterprises. Delhi provides businesses access to key government institutions, major corporate headquarters, and a vibrant marketplace that combines traditional trading expertise with contemporary business practices.",
      locationInfo: [
        {
          id: 1,
          cardAlt: "commercial office space - Baani The Statement, Gurgaon",
          metaTitle: "Premium Commercial Office Space in Gurgaon, Golf Course Road | UrbanWrk",
          metaDescription: "Experience Baani The Statement's contemporary office spaces in Gurgaon with UrbanWrk. Find flexible work solutions with stunning design and biophilic features for your business.",
          breadcrumbsTitle: "Baani The Statement",
          locationName: "Baani The Statement",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/baani-video.mp4",
          posterImage: "/images/locationInside/baani-poster.png",
          posterMobileImage: "/images/locationInside/technopolis-mobile-banner.png",
          locationCity: "Gurgaon",
          locationImg: NcrCard1,
          locationMobileImg: "/images/location/baani-mobile.png",
          location1: "Metro Station - 500 m",
          location2: "Airport - 13.6 km",
          location3: "One of India’s leading tech industry hub.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Gym, title: "Gym" },
            { source: Conference, title: "Outdoor space" },
          ],
          url: "/delhi/baani",
          amentiesBanner: "/images/locationInside/baani-amenities-banner.png",
          amentiesBannerAlt: "modern workplace",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Conference, title: "Outdoor space" },
            { img: Cafe, title: "Live kitchen" },
            { img: Phonebooth, title: "Phonebooth" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Cafe, title: "Live kitchen" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: Phonebooth, title: "Phonebooth" },
            { img: Gym, title: "Gym" },
            { img: GameRoom, title: "Game room" },
            { img: Conference, title: "Outdoor space" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
          ],
        },
        {
          id: 2,
          cardAlt: "modern office space in Max House Okhla",
          metaTitle: "Flexible & Managed Offices in Gurgaon, Max House | UrbanWrk",
          metaDescription: "UrbanWrk provides flexible office spaces in Gurgaon at Max House, ideal for solopreneurs and established businesses. Elevate your work experience with us.",
          breadcrumbsTitle: "Max House",
          locationName: "Max House",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/maxhouse-video.mp4",
          posterImage: "/images/locationInside/maxhouse-poster.png",
          posterMobileImage: "/images/locationInside/raheja-mobile-poster.png",
          locationCity: "Okhla",
          locationImg: NcrCard2,
          locationMobileImg: "/images/location/maxhouse-mobile.png",
          location1: "Metro Station - 1 km",
          location2: "Airport - 16.6 km",
          location3: "One of India’s leading tech industry hub.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Phonebooth, title: "Phonebooth" },
            { source: Access, title: "24x7 Access" },
          ],
          url: "/delhi/max-house",
          amentiesBanner: "/images/locationInside/maxhouse-amenities-banner.png",
          amentiesBannerAlt: "office space in Max House Delhi",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Conference, title: "Outdoor space" },
            { img: Cafe, title: "Cafetaria" },
            { img: Lounge, title: "Event spaces" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Cafe, title: "Cafetaria area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        }
      ],
    },
    {
      id: 5,
      bannerAlt: "workspace in Gurgaon",
      locationName: "Gurgaon",
      metaTitle: "Premium Ready-To-Work-In Office Spaces in Gurgaon | UrbanWrk",
      metaDescription: "UrbanWrk offers fully furnished, ready-to-work-in office spaces in the Gurgaon. Find your ideal workspace and transform your work environment with our premium offerings.",
      BannerImage: GurgaonBanner,
      locationDetail:
        "Gurgaon, often called the Millennium City, has transformed into one of India's premier business destinations. The city has become synonymous with corporate excellence, housing offices of numerous Fortune 500 companies and being the hub of India's private sector growth. Its modern infrastructure, including cyber parks, shopping complexes, and premium residential areas, creates an ecosystem that attracts global talent. The city's proximity to Delhi and the international airport, coupled with its cosmopolitan workforce, makes it an ideal location for businesses seeking a contemporary, globally-oriented environment.",
      locationInfo: [
        {
          id: 1,
          cardAlt: "commercial office space - Baani The Statement, Gurgaon",
          metaTitle: "Premium Commercial Office Space in Gurgaon, Golf Course Road | UrbanWrk",
          metaDescription: "Experience Baani The Statement's contemporary office spaces in Gurgaon with UrbanWrk. Find flexible work solutions with stunning design and biophilic features for your business.",
          breadcrumbsTitle: "Baani The Statement",
          locationName: "Baani The Statement",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/baani-video.mp4",
          posterImage: "/images/locationInside/baani-poster.png",
          posterMobileImage: "/images/locationInside/technopolis-mobile-banner.png",
          locationCity: "Gurgaon",
          locationImg: NcrCard1,
          locationMobileImg: "/images/location/baani-mobile.png",
          location1: "Metro Station - 500 m",
          location2: "Airport - 13.6 km",
          location3: "One of India’s leading tech industry hub.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Gym, title: "Gym" },
            { source: Conference, title: "Outdoor space" },
          ],
          url: "/gurgaon/baani",
          amentiesBanner: "/images/locationInside/baani-amenities-banner.png",
          amentiesBannerAlt: "modern workplace",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Conference, title: "Outdoor space" },
            { img: Cafe, title: "Live kitchen" },
            { img: Phonebooth, title: "Phonebooth" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Cafe, title: "Live kitchen" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: Phonebooth, title: "Phonebooth" },
            { img: Gym, title: "Gym" },
            { img: GameRoom, title: "Game room" },
            { img: Conference, title: "Outdoor space" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
          ],
        },
        {
          id: 2,
          cardAlt: "modern office space in Max House Okhla",
          metaTitle: "Flexible & Managed Offices in Gurgaon, Max House | UrbanWrk",
          metaDescription: "UrbanWrk provides flexible office spaces in Gurgaon at Max House, ideal for solopreneurs and established businesses. Elevate your work experience with us.",
          breadcrumbsTitle: "Max House",
          locationName: "Max House",
          bannerImage: "",
          mobileBanner: "",
          video: true,
          videourl: "/images/locationInside/maxhouse-video.mp4",
          posterImage: "/images/locationInside/maxhouse-poster.png",
          posterMobileImage: "/images/locationInside/raheja-mobile-poster.png",
          locationCity: "Okhla",
          locationImg: NcrCard2,
          locationMobileImg: "/images/location/maxhouse-mobile.png",
          location1: "Metro Station - 1 km",
          location2: "Airport - 16.6 km",
          location3: "One of India’s leading tech industry hub.",
          AmentiesData: [
            { source: Lounge, title: "Lounge area" },
            { source: Conference, title: "Conference rooms " },
            { source: Phonebooth, title: "Phonebooth" },
            { source: Access, title: "24x7 Access" },
          ],
          url: "/gurgaon/max-house",
          amentiesBanner: "/images/locationInside/maxhouse-amenities-banner.png",
          amentiesBannerAlt: "office space in Max House Gurgaon",
          connectivityAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Conference, title: "Conference rooms" },
            { img: Gym, title: "Gym" },
            { img: Conference, title: "Outdoor space" },
            { img: Cafe, title: "Cafetaria" },
            { img: Lounge, title: "Event spaces" },
          ],
          locationInsideAmenities: [
            { img: Lounge, title: "Lounge area" },
            { img: Cafe, title: "Cafetaria area" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN1.svg", title: "Conference rooms " },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN14.svg", title: "Event spaces" },
            { img: Phonebooth, title: "Phonebooth" },
            { img: "/images/locationInside/mail.svg", title: "Mail and packaging handling" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN6.svg", title: "24x7 Access" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN17.svg", title: "Cleaning services" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN7.svg", title: "IT rooms" },
            { img: "/images/solutionsLanding/logoAmenities/amenitiesN16.svg", title: "24/7 Security" },
          ],
        }
      ],
    },
  ],
};
